FROM python:3.8-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    gfortran \
    libatlas-base-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && \
    pip install "setuptools<81" "wheel" && \
    pip install --no-cache-dir cython==0.29.36 && \
    pip install --no-cache-dir numpy==1.21.6 scipy==1.9.3 && \
    pip install --no-cache-dir --no-build-isolation scikit-learn==0.23.0 && \
    pip install --no-cache-dir pandas==1.3.5 joblib==1.1.0

COPY sklearn_migrator/ ./sklearn_migrator/

COPY integration/input_scripts/ .
        
RUN mkdir -p /data /input
        
COPY integration/dataset_reg/ /data/
COPY integration/dataset_clf/ /data/
COPY integration/dataset_dim/ /data/
COPY integration/dataset_clu/ /data/
    
ENTRYPOINT ["python"]